"""
Add Constitutional Amendment Q race data to 2014 general election results.
Data transcribed from 2014ElectionReturn.pdf page 42.
"""

import csv

# Constitutional Amendment Q data
# Format: (county, candidate, party, votes)
# YES = For, NO = Against
amendment_q_data = [
    ('Aurora', 'Yes', '', 505),
    ('Aurora', 'No', '', 608),
    ('Beadle', 'Yes', '', 2754),
    ('Beadle', 'No', '', 2072),
    ('Bennett', 'Yes', '', 484),
    ('Bennett', 'No', '', 393),
    ('Bon Homme', 'Yes', '', 1185),
    ('Bon Homme', 'No', '', 1125),
    ('Brookings', 'Yes', '', 4877),
    ('Brookings', 'No', '', 4018),
    ('Brown', 'Yes', '', 6579),
    ('Brown', 'No', '', 5052),
    ('Brule', 'Yes', '', 875),
    ('Brule', 'No', '', 853),
    ('Buffalo', 'Yes', '', 249),
    ('Buffalo', 'No', '', 196),
    ('Butte', 'Yes', '', 1735),
    ('Butte', 'No', '', 1421),
    ('Campbell', 'Yes', '', 293),
    ('Campbell', 'No', '', 302),
    ('Charles Mix', 'Yes', '', 1467),
    ('Charles Mix', 'No', '', 1525),
    ('Clark', 'Yes', '', 727),
    ('Clark', 'No', '', 709),
    ('Clay', 'Yes', '', 2247),
    ('Clay', 'No', '', 1369),
    ('Codington', 'Yes', '', 4680),
    ('Codington', 'No', '', 4184),
    ('Corson', 'Yes', '', 409),
    ('Corson', 'No', '', 484),
    ('Custer', 'Yes', '', 2039),
    ('Custer', 'No', '', 1611),
    ('Davison', 'Yes', '', 3180),
    ('Davison', 'No', '', 2717),
    ('Day', 'Yes', '', 1137),
    ('Day', 'No', '', 1130),
    ('Deuel', 'Yes', '', 878),
    ('Deuel', 'No', '', 822),
    ('Dewey', 'Yes', '', 867),
    ('Dewey', 'No', '', 504),
    ('Douglas', 'Yes', '', 453),
    ('Douglas', 'No', '', 827),
    ('Edmunds', 'Yes', '', 932),
    ('Edmunds', 'No', '', 680),
    ('Fall River', 'Yes', '', 1619),
    ('Fall River', 'No', '', 1196),
    ('Faulk', 'Yes', '', 446),
    ('Faulk', 'No', '', 410),
    ('Grant', 'Yes', '', 1392),
    ('Grant', 'No', '', 1382),
    ('Gregory', 'Yes', '', 797),
    ('Gregory', 'No', '', 958),
    ('Haakon', 'Yes', '', 400),
    ('Haakon', 'No', '', 448),
    ('Hamlin', 'Yes', '', 990),
    ('Hamlin', 'No', '', 1141),
    ('Hand', 'Yes', '', 667),
    ('Hand', 'No', '', 778),
    ('Hanson', 'Yes', '', 621),
    ('Hanson', 'No', '', 654),
    ('Harding', 'Yes', '', 316),
    ('Harding', 'No', '', 286),
    ('Hughes', 'Yes', '', 4203),
    ('Hughes', 'No', '', 2640),
    ('Hutchinson', 'Yes', '', 1127),
    ('Hutchinson', 'No', '', 1536),
    ('Hyde', 'Yes', '', 278),
    ('Hyde', 'No', '', 312),
    ('Jackson', 'Yes', '', 491),
    ('Jackson', 'No', '', 665),
    ('Jerauld', 'Yes', '', 403),
    ('Jerauld', 'No', '', 385),
    ('Jones', 'Yes', '', 193),
    ('Jones', 'No', '', 264),
    ('Kingsbury', 'Yes', '', 1031),
    ('Kingsbury', 'No', '', 1024),
    ('Lake', 'Yes', '', 2595),
    ('Lake', 'No', '', 2030),
    ('Lawrence', 'Yes', '', 5425),
    ('Lawrence', 'No', '', 3401),
    ('Lincoln', 'Yes', '', 9963),
    ('Lincoln', 'No', '', 6423),
    ('Lyman', 'Yes', '', 704),
    ('Lyman', 'No', '', 496),
    ('Marshall', 'Yes', '', 893),
    ('Marshall', 'No', '', 766),
    ('McCook', 'Yes', '', 1041),
    ('McCook', 'No', '', 978),
    ('McPherson', 'Yes', '', 382),
    ('McPherson', 'No', '', 528),
    ('Meade', 'Yes', '', 4886),
    ('Meade', 'No', '', 3175),
    ('Mellette', 'Yes', '', 339),
    ('Mellette', 'No', '', 315),
    ('Miner', 'Yes', '', 398),
    ('Miner', 'No', '', 429),
    ('Minnehaha', 'Yes', '', 31089),
    ('Minnehaha', 'No', '', 21126),
    ('Moody', 'Yes', '', 1317),
    ('Moody', 'No', '', 975),
    ('Pennington', 'Yes', '', 19627),
    ('Pennington', 'No', '', 13324),
    ('Perkins', 'Yes', '', 597),
    ('Perkins', 'No', '', 712),
    ('Potter', 'Yes', '', 597),
    ('Potter', 'No', '', 514),
    ('Roberts', 'Yes', '', 1546),
    ('Roberts', 'No', '', 1506),
    ('Sanborn', 'Yes', '', 436),
    ('Sanborn', 'No', '', 389),
    ('Shannon', 'Yes', '', 1656),
    ('Shannon', 'No', '', 728),
    ('Spink', 'Yes', '', 1399),
    ('Spink', 'No', '', 1040),
    ('Stanley', 'Yes', '', 773),
    ('Stanley', 'No', '', 498),
    ('Sully', 'Yes', '', 388),
    ('Sully', 'No', '', 285),
    ('Todd', 'Yes', '', 1316),
    ('Todd', 'No', '', 760),
    ('Tripp', 'Yes', '', 1104),
    ('Tripp', 'No', '', 1033),
    ('Turner', 'Yes', '', 1557),
    ('Turner', 'No', '', 1608),
    ('Union', 'Yes', '', 3078),
    ('Union', 'No', '', 1816),
    ('Walworth', 'Yes', '', 898),
    ('Walworth', 'No', '', 916),
    ('Yankton', 'Yes', '', 4454),
    ('Yankton', 'No', '', 3041),
    ('Ziebach', 'Yes', '', 303),
    ('Ziebach', 'No', '', 288),
]

# Add to existing CSV
output_file = '2014/20141104__sd__general.csv'

with open(output_file, 'a', newline='') as f:
    writer = csv.writer(f)
    for county, candidate, party, votes in amendment_q_data:
        writer.writerow([county, 'Constitutional Amendment Q', '', party, candidate, votes])

print(f"Added {len(amendment_q_data)} Constitutional Amendment Q rows to {output_file}")
